version: "3.12"

services:
  app:
    container_name: shanks
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    ports:
      - "25:25"
      - "2525:2525"
